### ISSUE TITLE
@PostConstruct only works on public methods, forcing developers to expose implementation contracts

### ISSUE THREAD

**Issue by djessup** [unic/neba#106]
Since the `@PostConstruct` annotation only works on public methods (apparently by design, since it throws a helpful exception if you try to use it on a protected/private method) it ends up forcing you to apply it to a public method.

At least in my experience the nature of `@PostMapping` methods is well reflected by method names like `init()` or `setUp()` etc, since these are tasks that would normally be done at the end of a constructor or setter method in a traditional setting.

Making these methods public forces the developers hand and exposes initialisation methods that you wouldn't normally expect to form part of a public contract.

I think it would be a good enhancement to support using reflection to call private or protected post-mapping methods. It's also consistent with the field injection itself which obviously works on private fields. 

More generally this requirement could perhaps be obviated (at least in some cases) by performing setter injection and performing initialisation there - but I'd argue it's still valuable to be able to keep setup methods protected.

I'm happy to create a PR to implement this, but I wanted to get feedback first if you agree with this position.

**Comment by olaf-otto** [comment]
Hi @djessup - I absolutely agree that the contract of @PostMapping should be aligned to the contract used by @PostConstruct. There, it is stated:

    the method on which PostConstruct is applied MAY be public, protected, package private or private.

I think this says it all - I'm happy to review any post request.

**Comment by djessup** [comment]
Thanks Olaf, PR #107 over to you!

**Comment by olaf-otto** [comment]
Merged - done! Thanks a lot @djessup for the contribution!
