### ISSUE TITLE
RestController is not able to convert response body in json format

### ISSUE THREAD

**Issue by visittoravi1** [unic/neba#160]
I have created a rest controller like this - 

`@RestController

public class CategoryController {
    @RequestMapping(value = "/category/list", method = RequestMethod.GET)
    public List<String> sayHello() {
        return new Arrays.asList(new String[]{"A","B","C"});
    }
}`

This causes - 

`java.lang.IllegalArgumentException: No converter found for return value of type: class java.util.Arrays$ArrayList`

Whereas this code - 

`@RestController

public class CategoryController {
    @RequestMapping(value = "/category/list", method = RequestMethod.GET)
    public String sayHello() {
        return "Hello World!";
    }
}`

returns **Hello World!** and works as expected.

So the problem looks like spring is unable to convert a complex type to json

I have included jackson-databind, jackson-core and jackson-annotations. I also checked the bundle it has these jars in lib.

**Comment by olaf-otto** [comment]
Hi @visittoravi1 , thanks for reaching out!

Quick question: In your blueprint context XML file, did you configure MVC using `<mvc:annotation-driven />`? This is required for Spring to detect the presence of jackson and setup the corresponding converters.

Regards,
Olaf

**Comment by olaf-otto** [comment]
Hi @visittoravi1, 

I have created a test implementation using the code you provided in the neba sample project, see [https://github.com/unic/neba-sample-project/tree/neba-160](https://github.com/unic/neba-sample-project/tree/neba-160), see [https://github.com/unic/neba-sample-project/blob/neba-160/src/main/java/to/adapt/neba/impl/neba160/CategoryController.java](https://github.com/unic/neba-sample-project/blob/neba-160/src/main/java/to/adapt/neba/impl/neba160/CategoryController.java). This seems to work as expected - does this match your use case?

Regards,
Olaf

**Comment by visittoravi1** [comment]
Hi @olaf-otto thanks for your reply.

Yes i have included <mvc:annotation-driven /> in my blueprint context xml.

I will test code given by you and get back very soon.

**Comment by visittoravi1** [comment]
Hi @olaf-otto Indeed your code works. 
Problem with my code is it's not a launchpad application. I am creating a bundle and deploying to sling with maven-sling-plugin. Let me figure out why one earth my code doesn't work.

**Comment by olaf-otto** [comment]
Hi @visittoravi1

thanks, let me know when there is anything I can do to be of assistance! 

In my experience, issues with the data converters with auto discovery often stem from issues with class loading / load order, which can be tricky (especially with OSGI). I sometimes debug Spring's AnnotationDrivenBeanDefinitionParser to see if the static jackson2Present member is true and whether the corresponding data type converters are initialized as expected.

Hope that helps,
Olaf

**Comment by joaotab** [comment]
Hi @visittoravi1 

   Don't known which version of NEBA / Spring you're using but since version 4 Spring also supports Gson.

   I've done something similar but had to manually register the converter in the context.xml like so:

    <bean id="gsonHttpMessageConverter" class="org.springframework.http.converter.json.GsonHttpMessageConverter"/>

    <bean id="handlerAdapter"  
class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">

        <property name="messageConverters">
            <list>
                <ref bean="gsonHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.ByteArrayHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.xml.SourceHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.FormHttpMessageConverter"/>
                <bean class="org.springframework.http.converter.StringHttpMessageConverter"/>
            </list>
        </property>
    </bean>

Not sure this is the best way to do it but I found no way of setting this without having to override everything and register all default converters as well.

Should work for Jackson as well if you adjust the Json HTTP converter class.

Cheers,
João

**Comment by visittoravi1** [comment]
Hi @joaotab 

I tried your solution adding gsonHttpMessageConverter bean by myself but then i get error like - 

`
java.lang.ClassNotFoundException: com.google.gson.JsonParseException not found by io.neba.spring-web [130]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

I tried the same with jackson mapper as well and in this case i got error  like - 
`
java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException not found by io.neba.spring-web [130]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1558)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

In both the cases it says ClassNotFound by io.neba.spring-web

So my best guess is these libraries are not added as part of **neba bundle itself** 

In your code( using launchpad ) it worked because you have added **jackson** library in classpath and it was available at the time of starting Neba bundle.

I have shared a minimal source required source code here - https://github.com/visittoravi1/neba-spring-example.git

Please have look if you got time. It has required description how to build and run the code. I have not included httpMessageconverter in this code so that it only throws **No converter found error**. You can try adding this code in context.xml and you will see above error.
`
<bean id="gsonHttpMessageConverter"
		class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter" />

	<bean id="handlerAdapter"
		class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">

		<property name="messageConverters">
			<list>
				<ref bean="gsonHttpMessageConverter" />
				<bean
					class="org.springframework.http.converter.ByteArrayHttpMessageConverter" />
				<bean
					class="org.springframework.http.converter.xml.SourceHttpMessageConverter" />
				<bean class="org.springframework.http.converter.FormHttpMessageConverter" />
				<bean
					class="org.springframework.http.converter.StringHttpMessageConverter" />
			</list>
		</property>
	</bean>
`
Expecting to hear from you. Thanks.

**Comment by olaf-otto** [comment]
Hi @visittoravi1,

Thanks for providing the sample -  I am looking into it now.

Regards,
Olaf

**Comment by olaf-otto** [comment]
Hi @visittoravi1 

I fixed the issue. To clarify:

- NEBA itself does not depend on jackson / gson, but the Spring bundles have optional dependencies to these bundles
- The Spring bundles shipped with NEBA do not package-import these dependencies. Instead, they have been modified to import the entire bundles if they are present. This is because Sling / AEM versions shipped with *partial* or even duplicate versions of these packages, which led to failures and classloading issues. Thus, the thirdparty bundles must be installed, embedding the dependencies and exporting them is not an option.

To achieve this, I have added a "delivery" bundle to your sample project that deploys the thirdparties (jackson etc.), neba and your own app in a controller order. Then, all dependencies are resolved correctly and your example works fine, see [https://github.com/visittoravi1/neba-spring-example/pull/2](https://github.com/visittoravi1/neba-spring-example/pull/2)

To run it, mvn clean install your app, the mvn clean install the delivery module, this will install the delivery bundle to your local sling instance. I am assuming you are using a local sling launchpad 8 for this.

Hope that helps!
Kind regards,
Olaf

**Comment by visittoravi1** [comment]
Thank you very much @olaf-otto . Thanks for explaining the problem and once again thanks for recommending a neat and clear solution. I merged your pull request and it works seamlessly. Closing this one and hope to be in touch.

**Comment by olaf-otto** [comment]
Hi @visittoravi1,

I'm glad to hear I could help!

Kind regards,
Olaf

**Comment by joaotab** [comment]
Hi @visittoravi1,

   Sorry I forgot to mention I was using AEM which comes bundled with gson.

   Glad to hear @olaf-otto solved it for you.

   Cheers,

      João

**Comment by longpingping** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter': Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'java.util.ArrayList' to required type 'java.util.List' for property 'messageConverters'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter' to required type 'org.springframework.http.converter.HttpMessageConverter' for property 'messageConverters[0]': no matching editors or conversion strategy found
