### ISSUE TITLE
How to inject an osgi service in controller

### ISSUE THREAD

**Issue by visittoravi1** [unic/neba#161]
I am using neba with my sling bundle.

Problem is i am not able to inject an osgi service into my controller.

Here is the problem statement - 
I have a service like this - 

```
@Component(metatype = true, immediate = true, enabled = true)
@Property(name = "title", value = "Hello World Service")
@Service
public class HelloWorldServiceImpl implements HelloWorldService{
	
	private static final Logger LOGGER = LoggerFactory.getLogger(HelloWorldServiceImpl.class);
	
	@Reference
	private ResourceResolverFactory resolverFactory;

	@Override
	public String sayHello() {
		return "HelloWorld!";
	}
}

```

Now here is my servlet - 

```
@SlingServlet(paths = "test", selectors = "hello", extensions = "html", methods = "GET")
@Properties({ @Property(name = "resource.type", value = "ui:news:view") })
public class TestServlet extends SlingAllMethodsServlet{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private static final Logger LOGGER = LoggerFactory.getLogger(TestServlet.class);
	
	@Reference
	private HelloWorldService helloWorldService;
	
	@Override
	protected final void doGet(final SlingHttpServletRequest request, final SlingHttpServletResponse response)
			throws IOException {
		PrintWriter pw = response.getWriter();
		try{
			pw.print(helloWorldService.sayHello());
		}catch(Exception ex){
			ex.printStackTrace(pw);
		}finally{
			pw.flush();
			pw.close();
		}
	}
}
```
The servlet works just fine and gives me result - **HelloWorld!** by accessing url 
http://localhost:8080/apps/test
Now here is my controller

```
@RestController
public class HelloController {

        @Reference
	private HelloWorldService helloWorldService;
	
	@RequestMapping(value="/hello",method=RequestMethod.GET)
	public String sayHello(){
		return helloWorldService.sayHello();
	}
}
```
Now accessing controller with url - 
http://localhost:8080/bin/mvc.do/hello
gives me NullPointerException on line -** return helloWorldService.sayHello();**
Because It is not able to inject **HelloWorldService**

**Comment by joaotab** [comment]
Hi Ravi,

   The way I got it to work was by adding a reference in the osgi-context.xml file:

<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0
   https://osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <reference id="helloWorldServiceClient"
               interface="....HelloWorldService"/>
</blueprint>

(You have to use the FQDN of your HelloWorldService interface)

Hope it helps.

Cheers,

   João

**Comment by visittoravi1** [comment]
Hi @joaotab ,
Thanks for your answer, but i need some more clarity on it.
1. 
Here is my context.xml in **OSGI/blueprint**
```<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:bp="http://www.osgi.org/xmlns/blueprint/v1.0.0"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
   http://www.springframework.org/schema/beans/spring-beans-4.2.xsd
   http://www.osgi.org/xmlns/blueprint/v1.0.0
   http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd
   http://www.springframework.org/schema/context
   http://www.springframework.org/schema/context/spring-context-4.2.xsd
   http://www.springframework.org/schema/mvc
   http://www.springframework.org/schema/mvc/spring-mvc-4.2.xsd
   http://www.eclipse.org/gemini/blueprint/schema/blueprint-compendium
   http://www.eclipse.org/gemini/blueprint/schema/blueprint-compendium/gemini-blueprint-compendium.xsd">

	<context:component-scan base-package="com.ttn.aem.news.controllers" />

	<mvc:annotation-driven />
</beans>
```

so in order to write - 

```
<reference id="helloWorldServiceClient"
           interface="com.osgi.neba.example.HelloWorldService"/>
```
we need namespace of reference as well like we do for **mvc, context** etc, if so what's that namespace?

2. after adding this line in context.xml **@Reference** will be enough to autowire the service in controller?

**Comment by joaotab** [comment]
Hi Ravi,

   I believe there's an example in the neba sample project on github:

https://github.com/unic/neba-sample-project/blob/master/src/main/resources/OSGI-INF/blueprint/context.xml

   Or you can have the blueprint part as a separate file as suggested in the Gemini Blueprint docs:

http://www.eclipse.org/gemini/blueprint/documentation/reference/1.0.2.RELEASE/html/app-deploy.html#app-deploy%3aheaders.

   One thing I forgot to mention is that I had to use @Autowired after adding the reference in the xml to inject the Service in the Controller.

   Cheers,

      João

**Comment by joaotab** [comment]
Updated my previous reply, forgot to use a code block to properly format the xml

**Comment by visittoravi1** [comment]
Hi @joaotab ,

I just overlooked the configuration. It has comments saying this part is used to wire services into the spring context.

```
<bp:blueprint>
		<bp:reference interface="com.ttn.aem.news.service.CategoryService" id="categoryService"></bp:reference>
	</bp:blueprint>
```
This line did the job and yes @Autowired or @Resource both works fine in controller.
Thank you again and apology for not giving enough time to go through the example to understand how it works.

You might like to mark it as **question** rather an **issue**, I am not able add tag.
So please add tag **question** and close it. or just confirm after adding i will close it.

**Comment by olaf-otto** [comment]
Hi @visittoravi1 the blueprint namespace is the correct one. As a background, @Autowired / @Inject etc. inject beans from the application context. Thus, anything that shall be injected must be in the application context. In the case of OSGi services, these must thus be imported into the application context beforehand. As @joaotab correctly pointed out, this is done using the blueprint namespace via the bp:reference is the right way to do so.

Thanks a lot for this great discussion and thanks to @joaotab for pointing to the right solution!
