### ISSUE TITLE
Append parameter for @ResourceParam

### ISSUE THREAD

**Issue by huberchrigu** [unic/neba#18]
@Children and @Reference support now "append" parameters, which allow appending a relative path to the resulting resource(s). Why not supporting the same for @ResourceParam.

Example:
@RequestMapping
public void handleRequest(@ResourceParam(append = "jcr:content") MyPageModel path) {}

This would simplify the following:
@RequestMapping
public void handleRequest(@ResourceParam Resource path) {
 Resource jcrContentResource = path.getChild("jcr:content");
 if (jcrContentResource != null) {
  MyPageModel myPageModel = jcrContentResource.adaptTo(MyPageModel.class);
}

**Comment by olaf-otto** [comment]
Very good idea - this also makes the application of appendable paths more consistent throughout the API.

Pull request is ready:
https://github.com/unic/neba/pull/30

**Comment by olaf-otto** [comment]
Implemented - done!
