### ISSUE TITLE
Model resource for PlaceholderVariableResolver

### ISSUE THREAD

**Issue by huberchrigu** [unic/neba#19]
In most cases we could make use of a PlaceholderVariableResolver, the variable depends on the request context, or on the resource model for whom the placeholder resolver is requested. So what about extending the PlaceholderVariableResolver API by

public String resolve(String variableName, Resource resource);

Or maybe rather defining an super type of PlaceholderVariableResolver to support both variants and to be compliant to older NEBA versions.

**Comment by olaf-otto** [comment]
IMO, this is not such a great idea - if the data depends on the resource itself, if should rather be modeled using an annotation on the resource model, not a placeholder variable. The placeholder is essentially something to be resolved in the application context, not the resolution scope.
