### ISSUE TITLE
Make logfile and number of line selection bookmarkable in the log file viewer

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#24]
The logfile viewer allows selecting a logfile and a number of files to view. If the list of logfiles is very long, re-selecting the suitable logfile can be cumbersome. Also, it is not possible to share the selection at the moment. It would thus be a great improvement to be able to bookmark this selection along with the number of lines specified.

**Comment by michal-ociepka** [comment]
Hello Olaf,
Did you already add this enhancement into 3.5.0?
I cannot find it there (log file viewer + OSGi configuration).
