### ISSUE TITLE
Non-deterministic filter chain breaks i18n

### ISSUE THREAD

**Issue by notizklotz** [unic/neba#247]
AEM 6.3.1.2 uses a default ranking of 10000 for Sling's I18NFilter. As Neba 4.3.2 uses the same for Spring's RequestContextFilter this leads to a non-deterministic filter chain.

I had one instance where I18NFilter was ordered de facto after RequestContextFilter which broke request.getResourceBundle() semantics:
```
10000 : class org.springframework.web.filter.RequestContextFilter (id: 10650, property: service.ranking=10000); called: 1402; time: 1602ms; time/call: 1142µs
10000 : class org.apache.sling.i18n.impl.I18NFilter (id: 2830, property: service.ranking=10000); called: 1406; time: 7ms; time/call: 4µs
9999 : class io.neba.core.resourcemodels.caching.RequestScopedResourceModelCache (id: 10648, property: service.ranking=9999); called: 1402; time: 9ms; time/call: 6µs
```

I fixed the problem by increasing priority of the I18NFilter.

As a (more) permanent solution I suggest Neba uses the following defaults:
9100 class org.springframework.web.filter.RequestContextFilter
9000 class io.neba.core.resourcemodels.caching.RequestScopedResourceModelCache

**Comment by olaf-otto** [comment]
Thanks a lot for this report @notizklotz! This issue arises because sling decorates the request with I18n capabilities by wrapping it. Thus, if the sling RequestContextFilter is invoked to early, it provides a request (via a ThreadLocale) that does not have I18n capabilities.

**Comment by olaf-otto** [comment]
Fixed in NEBA 5..
