### ISSUE TITLE
PATCH support for Spring in NEBA

### ISSUE THREAD

**Issue by ivoleitao** [unic/neba#251]
Hi,

I've noticed that Neba extends SlingAllMethodsServlet which does not support PATCH method for REST API [calls](https://github.com/apache/sling-org-apache-sling-api/blob/master/src/main/java/org/apache/sling/api/servlets/SlingAllMethodsServlet.java#L132) Any way to enabled it in NEBA ?

I'm delivering a fully REST API over Sling and therefore I need this method.

Tnks in advance,
Regards,
Ivo Leitão

**Comment by olaf-otto** [comment]
Hi @ivoleitao 

Absolutely - I'll open up a ticket and include it i the upcomign 5.0 release!

Kind regards,
Olaf

**Comment by ivoleitao** [comment]
Hi Olaf,

Tnks a lot,
Regards,
Ivo Leitão

**Comment by olaf-otto** [comment]
Implemented, done. Will be release with 5.0 shortl!
