### ISSUE TITLE
Release-Notes 5.0.0 Doc: Wrong link to documentation

### ISSUE THREAD

**Issue by olimination** [unic/neba#255]
On the following release notes page:
https://neba.io/2018/07/16/neba-release-5.0.0.html

the following link does not work for "OSGi bundle header Neba-Packages":
http://localhost:4000/documentation.html#add_neba_packages_header

I think this should be:
https://neba.io/documentation.html#add_neba_packages_header

**Comment by olaf-otto** [comment]
Fixed! 
Thanks Svenska Järnvägen Form the great  WiFi in the x2000 😀
