### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by DaniRey** [unic/neba#394]
Let's get rid of all master-slave terminology #BlackLivesMatter

More details on how and why we want this change https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

Updating local clones

If someone has a local clone, then can update their locals like this:

$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main

Changing target branch for open PRs according to https://stackoverflow.com/a/24159161/3768943

**Comment by olaf-otto** [comment]
Done!
