### ISSUE TITLE
@Reference append parameter does not work with "relative notation"

### ISSUE THREAD

**Issue by huberchrigu** [unic/neba#42]
```
@Reference(append = "/jcr:content")
private Resource pageContent; // this works!

@Reference(append = "jcr:content")
private Resource pageContent2; // this does not work!
```

Above example makes no sense in my oppinion. Actually a relative path in Sling normally starts without a slash `/`, so "jcr:content" as append value makes more sense. But this does not work.

**Comment by olaf-otto** [comment]
Fixed!
