### ISSUE TITLE
neba.io: Huge Activity Feed

### ISSUE THREAD

**Issue by thedodobird2** [unic/neba#44]
The Activity Feed just got quite a bit larger (vertically), because of one huge "activity"-message. Now the slider-arrows are not where they should be. I think this should be fixed in some way.

A solution could be, to set a character limit and instead of the rest of the "activity"-message, add "..." to the end.
Or the arrows should be placed further up.

What happened:
![2015-03-05 13-10-52_neba - the best of sling powered by spring](https://cloud.githubusercontent.com/assets/10851587/6504577/1fe818ca-c339-11e4-95b0-0e6cd639216c.png)

The problematic message:
![2015-03-05 10-32-24_neba - the best of sling powered by spring](https://cloud.githubusercontent.com/assets/10851587/6504249/7df1ca8c-c335-11e4-8c01-4f6145758d52.png)

**Comment by olaf-otto** [comment]
We've removed the activity feed from neba.io - this is thus no longer an issue,
