### ISSUE TITLE
AnnotationFieldMapper does not work on primitive types

### ISSUE THREAD

**Issue by huberchrigu** [unic/neba#54]
I wanted to create a field mapper for fields of type boolean. The problam is that I cannot use the boolean (primitive) type. NEBA does then not call the AnnotationFieldMapper, and I cannot parameterize the field mapper with <boolean>, as this does not work for primitive types. So I think when a field mapper provides the field type Boolean (or Integer, Long, ...), it should also be called for primitive types (boolean, int, long, ...). Just like the other NEBA annotations are handled.

**Comment by olaf-otto** [comment]
Pull request: #55
