### ISSUE TITLE
Improve labels in model registry

### ISSUE THREAD

**Issue by DaniRey** [unic/neba#64]
Currently the labels in the model registry (see */system/console/modelregistry*) are misleading and should be improved.

*Filter: mapping to*
is used to filter the models by only showning those which can map the resource behind the given path. 

**Suggestion**
Only show models that can map the (resource belonging to the) path [/content...]

*Filter: compatible to*
is used to filter the models, by only showing does which could be cast to a certain (super-)class or interface. Basically only showing those for which "instanceof" would return true. 

**Suggestion**
Only show models that can be cast to [class/interface]

**Comment by olaf-otto** [comment]
Indeed, the labels can be improved. However, there is very limited space in the console, thus long texts are not a good option. I'd rather go with

"adaptable from" for the resource path and "assignable from", as those are well defined technical terms. In addition, I would provide a placeholder text in the form fields illustrating the expected input.

**Comment by olaf-otto** [comment]
Implemented - done!
