### ISSUE TITLE
AnnotatedFieldMapper doesn't allow implementations of the same @Annotation from different bundles

### ISSUE THREAD

**Issue by djessup** [unic/neba#67]
I've been trying to track down a strange bug since refactoring a couple of AEM projects I work on, and have traced it down to a behaviour in `io.neba.core.resourcemodels.mapping.AnnotatedFieldMappers`.

My situation is:
* I have three projects (i.e. OSGi bundles), we'll call them "project1", "project2" and "shared".
* In the "shared" project I define an annotation `@MyAnnotation` and 3 `AnnotatedFieldMapper`'s to handle various usages of that annotation
* In "project1" I use these annotations
* In "project2" I use these annotations, but also define an additional `AnnotatedFieldMapper` for another use-case of the annotation, specific to that project.
* (Before refactoring, no annotations were defined in "shared", and "project1" and "project2" had their own separate implementations)

The bug I have is that if I install "project2" after I install "shared", the `AnnotatedFieldMapper`'s in "shared" stop working, and visa-versa if I install "shared" after "project2".

This happens because `AnnotatedFieldMappers#remove` calls:
```
this.fieldMappers.remove(mapper.getAnnotationType());
```
Which removes all mappers matching the annotation type (e.g. `@MyAnnotation`) and not just the specific mapper being unbound.

I can (and I think will have to in the short term at least) refactor my code to work around this behaviour, but it feels like it may be an unintended behaviour?

I'm happy to listen to any good arguments that I'm misusing `AnnotationFieldMapper`'s if that is indeed the case, otherwise this seems like it could be a fairly straightforward fix by doing a deep comparison of the mapper being unbound against the cache of registered mappers.

**Comment by DaniRey** [comment]
We never used the AnnotationFieldMapper in such an exhaustive way and therefore never stumbled upon this bug. Thanks for spotting that. 

I think the ConcurrentDistinctMultiValueMap should be enriched with a removeSingle method. It's signature should contain the key and a single value. 

As I am currently on holiday (and afaik Olaf as well),  we can not immediately work on this. 

As neba is an open source project, you might fix it yourself and issue a pull request. This would give you the possibility to work with your own version of neba in the meantime, instead of reverting your refactoring.

**Comment by olaf-otto** [comment]
Thanks for reporting this! I'm available this week and will start to work on this now. I'll open a feature braanch and create a test case reproducing the issue.

**Comment by olaf-otto** [comment]
Fix ready, pull request pending

**Comment by djessup** [comment]
You guys are quick – thanks!

I'll try building the feature branch and testing it against my problem code.

**Comment by djessup** [comment]
Looking good here - if I set a breakpoint in the add/remove methods I can see the correct mappers being added/removed now.

Thanks again!

**Comment by olaf-otto** [comment]
Perfect, thank you for testing!

**Comment by olaf-otto** [comment]
Merged #68 - fixed! Thanks everyone!
