### ISSUE TITLE
Remove velocity support

### ISSUE THREAD

**Issue by olaf-otto** [unic/neba#86]
NEBA uses Apache Velocity to support _rendering beyond resources_ (http://neba.io/userguide.html#using-velocity). However, there has been no update for velocity since 2010 (https://velocity.apache.org/). Furthermore, almost all uses of bean rendering seen in practice were not as intended. For instance, velocity views are used to render resource models or data otherwise stemming from resources. 

With the availability of a Sightly as a powerful templating language, velocity support shall thus be removed from NEBA. Users of velocity are thus encouraged to transition to the use of Sightly, the JSP expression language or custom tag libraries instead.

**Comment by olaf-otto** [comment]
Done!

**Comment by DaniRey** [comment]
Hi @olaf-otto 

I can't see a related commit. Did you miss to reference the issue when committing?

Cheers
Dani

**Comment by olaf-otto** [comment]
This one: https://github.com/unic/neba/commit/8378f995e73286082033739887ea46f6446a04ce

**Comment by olaf-otto** [comment]
Perhaps I should transition to the format #xyz here...
