### ISSUE TITLE
PostConstruct annotation does not behave properly with ResourceParam annotation

### ISSUE THREAD

**Issue by olimination** [unic/neba#93]
We use in a Spring MVC controller following parameter in a method:

```java
@ResourceParam MyPageImpl page
```
The `MyPageImpl`has an "init" method annotated with the `@PostConstruct`. In this init method we access some mapped properties.

Following resource model properties are defined via Neba annotations:

```java
@This
private Resource resource;
@Path("jcr:content")
private Resource pageContent;
...
@PostConstruct
public void init() {
  // doing some init code stuff accessing also some properties defined above
}
```

If the code tries to access the `pageContent`property for example it throws a NPE in the PostConstruct method. 

The workaround is:
Call this init method once again in the calling controller method:

```java
@RequestMapping(value = "/comments", produces = JSON)
@ResponseBody
public String getComments(@ResourceParam MyPageImpl page) throws Exception {
    page.init();
    ...   
}
```

Could it be that during handling the `@ResourceParam` the `@PostConstruct` is not handled properly or somehow too early?

We use Neba 3.5.0

**Comment by DaniRey** [comment]
Unfortunately your code snippet doesn't contain the @PostConstruct annotation, therefore I'm not sure where exactly you use it.

Anyway I guess that you inteded to use @PostMapping and choose @PostConstruct by mistake. PostConstruct is a javax annotation and should be called by Spring after construction. This would then be before Neba finished the mapping (in case it was used within a ResourceModel)

Can you try again using the @PostMapping annotation provided by Neba?

**Comment by olimination** [comment]
Ouhhh yes you're right :)

I mixed up with `@PostConstruct` and `@PostMapping`.

WIth PostMapping it works of course :)

Thank you for the hint!
